build:
  command: |
    curl -s https://pyenv.run | bash
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    pyenv install 3.10.13
    pyenv global 3.10.13
    pip install -r requirements.txt
